### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by owodo** [snigui/materials#2]
When I opened the localhost on the port 3050. I got the following message
![WelcomePage-middlePanelMessage](https://user-images.githubusercontent.com/52643989/95698398-d145fe00-0c0f-11eb-9150-ae7e42c9ffd5.png)

This message still persists after one filter is defined
![OneFilter-ErrorMessage](https://user-images.githubusercontent.com/52643989/95698432-e884eb80-0c0f-11eb-98fc-b27af6b4174b.png)

**Comment by snigui** [comment]
So the vizier db server is on maintenance which is why the data doesn't load because the url request sent to it doesn't connect to the vizier db server. Michael said it would be fixed soon
