### ISSUE TITLE
First view

### ISSUE THREAD

**Issue by owodo** [snigui/materials#3]
When I loaded the app, I got the following error (callback error)

![image](https://user-images.githubusercontent.com/52643989/95897118-ff842480-0d5a-11eb-9705-d6db4a179a1e.png)

**Comment by snigui** [comment]
So for that can you try reloading twice (like cmd+r twice?)

**Comment by owodo** [comment]
It seems I needed to wait till the data is loaded (top panel of middle column). Is there a way to check if data is loaded - and only then display the figure?

**Comment by snigui** [comment]
yeah there should be a way, I will try to figure out how to load scatter plot after table is loaded!

**Comment by snigui** [comment]
Fixed. It should refresh after the error on its own, please give it 3 seconds max. Let me know if it is any better!
