### ISSUE TITLE
Filter does not work

### ISSUE THREAD

**Issue by owodo** [snigui/materials#6]
I build two filters but I do not see any of them work for the top panel in the middle column. One of the filters seems to be respected in the plot (bottom panel of the middle column). See attached. 

![image](https://user-images.githubusercontent.com/52643989/96357018-edd8af00-10c3-11eb-8f69-b0f2583e6493.png)

**Comment by snigui** [comment]
Okay so ABS_wf_D doesn't seem to work? Thank you for letting me know! I will take a look. I'm also working on the first view, will report back on these on Tuesday during the meeting.

**Comment by snigui** [comment]
so when I try it, I get an empty table indicating that ABS_wf_D does not exist <= 0.1. Can you please try again and let me know if you get empty table or not

**Comment by snigui** [comment]
this should be the output:
![image](https://user-images.githubusercontent.com/40993241/96471129-fc76b180-11fc-11eb-9c4f-232023c2792a.png)
If you remove filter and hit submit, it should go back to normal

**Comment by snigui** [comment]
Also, if you only edit a preexisting filer, the change won't show because the "Add filter" button has to be clicked. So you can remove a filter and add a new one instead of editing an old one. I also added CLEAR ALL button to entirely reset all filters!

**Comment by owodo** [comment]
I tried again on https://morph.odin.cse.buffalo.edu/
and the filter did not work for me (this was the first filter I tried).

![image](https://user-images.githubusercontent.com/52643989/96592165-1a541d00-12b6-11eb-84df-7877ce092f22.png)

**Comment by snigui** [comment]
Did you click on add filter? They won't work unless you click on add filter and hit submit (which will also make a new filter box when you click add filter)

**Comment by owodo** [comment]
Yes, now it worked. But this was not intuitive to me. Is there a way to apply the filter when Submit-button is pressed?

**Comment by snigui** [comment]
Okay I'll try

**Comment by snigui** [comment]
I fixed it so when you press submit now, the filters are applied! Please try it. You can click add filter for the first time and then click submit to apply it and from there on you can edit the ones you have already added and just click submit for it to apply
